# Generated by Django 2.1.7 on 2019-02-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190213_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mdp',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=14, verbose_name='Telephone'),
        ),
    ]
