# Generated by Django 2.1.7 on 2019-02-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190213_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mdp',
            field=models.CharField(max_length=50, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=14, unique=True, verbose_name='Telephone'),
        ),
    ]
